#!/usr/bin/env bash
# This script is to print Best School 10 times and hi before the last
i=1
while [ $i -le 20 ]
do
	case $i in
		5)
			echo "bad luck from China"
			;;
		10)
			echo "bad luck from Japan"
			;;
		18)
			echo "bad luck from Italy"
			;;
		*)
			;;
	esac
	echo $i
	((i++))
done
